### PR TITLE
add #ifdef __APPLE__ to make compilable on OSX

### PR DESCRIPTION
**Pull request by dokipen3d**
I've added an #ifdef to make it possible to compile on OSX using a gcc from homebrew.

### CODE REVIEW

**Comment by ProGTX** [comment]
Thank you very much! I am unable to test this because I don't have OS X, but I guess this works for you, which is great. Did you have any other difficulties on OS X?

**Comment by dokipen3d** [comment]
Well it compiled and I started to run the test program smallpt but I didn't have time to let it run fully. The device read out worked though. I'll set it off tonight and see how it goes

**Comment by dokipen3d** [comment]
Here are the results of the tests in the regression folder.....

There seem to be some issues. Also the runtime defaults to the intel integrated graphics and not the dedicated nvidia 650m.  I'm not sure how to specify that. 

./access_sycl_cl_types 
Debug: add 0x7fff5a335340 0x7fff5a335410 
Debug: add 0x7fff5a335340 0x7fff5a335410 
Debug: add 0x7fff5a335340 0x7fff5a335410 
Debug: add 0x7fff5a335340 0x7fff5a335410 
0, 0
1, 1
2, 2
3, 3
4, 4
5, 5
6, 6
7, 7

./anatomy_sycl_app_parallel_for 
Queue device information: 
HD Graphics 4000 
OpenCL C 1.2  
FULL_PROFILE 
OpenCL 1.2  
1.2(Jun 30 2016 20:43:33) 


Compiled kernel: 
__kernel void _sycl_kernel_0(__global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf1[_sycl_gid] = _sycl_gid;
}
 
Debug: can_flush buffers_in_use 0x7fff58aa2f90 
Debug: can_flush host_accessors 
Debug: can_flush buffers_in_use 0x7fff58aa2f90 
Debug: can_flush host_accessors 
Debug: optimize 
Debug: flush 0x7f86ba714b70 0x7f86ba431190 
command: init 
command::type::get_accessor 0x7fff58aa2f90 mode::write target::global_buffer 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_0 
command::type::copy_data 0x7fff58aa2f90 mode::write target::global_buffer mode::read

./naive_square_matrix_rotation 
Queue device information: 
HD Graphics 4000 
OpenCL C 1.2  
FULL_PROFILE 
OpenCL 1.2  
1.2(Jun 30 2016 20:43:33) 


Initializing buffer A 
Debug: add 0x7fff58984560 0x7fff589843b0 
Debug: add 0x7fff58984560 0x7fff589843b0 
Submitting work 
Compiled kernel: 
__kernel void _sycl_kernel_0(__global const float* _sycl_buf1, __global float* _sycl_buf2) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid1 = get_global_id(1);
	const int _sycl_gid = _sycl_gid1 * get_global_size(0) + _sycl_gid0;
	_sycl_buf2[((128 - _sycl_gid1) - 1) + _sycl_gid0 * 128] = _sycl_buf1[_sycl_gid];
}
 
Debug: can_flush buffers_in_use 0x7fff589843b0 0x7fff58984430 
Debug: can_flush host_accessors 
Debug: can_flush buffers_in_use 0x7fff58984430 
Debug: can_flush host_accessors 
Debug: optimize 
Debug: flush 0x7f81b2f061e0 0x7f81b2d030f0 
command: init 
command::type::get_accessor 0x7fff589843b0 mode::read target::global_buffer 
command: init 
command::type::get_accessor 0x7fff58984430 mode::write target::global_buffer 
command::type::copy_data 0x7fff589843b0 mode::read target::global_buffer mode::write 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_0 
command::type::copy_data 0x7fff58984430 mode::write target::global_buffer mode::read 
Done, checking results 
Debug: add 0x7fff589844b0 0x7fff589843b0 
Debug: add 0x7fff589844b0 0x7fff589843b0 
Debug: add 0x7fff58984560 0x7fff58984430 
Debug: add 0x7fff58984560 0x7fff58984430

./random_number_generation 
Queue device information: 
HD Graphics 4000 
OpenCL C 1.2  
FULL_PROFILE 
OpenCL 1.2  
1.2(Jun 30 2016 20:43:33) 


Compiled kernel: 
__kernel void _sycl_kernel_0(__global float* _sycl_buf1) {
	uint2 _uint2_0 = (uint2)(24325, 32536);
	int _int_0 = 0;
	for(; (_int_0 < 4096); (++_int_0)) 
	{ 
		float _float_0 = 2.32831e-10f;
		_uint2_0.s0 = ((((_uint2_0.s0 * 17) + (_uint2_0.s1 * 13123)) << 13) ^ ((_uint2_0.s0 * 17) + (_uint2_0.s1 * 13123)));
		_uint2_0.s1 ^= (((_uint2_0.s0 * 17) + (_uint2_0.s1 * 13123)) << 7);
		float _float_1 = (((((_uint2_0.s0 * 17) + (_uint2_0.s1 * 13123)) * (((((_uint2_0.s0 * 17) + (_uint2_0.s1 * 13123)) * ((_uint2_0.s0 * 17) + (_uint2_0.s1 * 13123))) * 15731) + 74323)) + 871483) * _float_0);
		_sycl_buf1[_int_0] = _float_1;
	} 
}
 
Debug: can_flush buffers_in_use 
Debug: can_flush host_accessors 
Debug: can_flush buffers_in_use 0x7fff56c27290 
Debug: can_flush host_accessors 
Debug: optimize 
Debug: flush 0x7fc4e8c15ae0 0x7fc4e8f2cdb0 
command: init 
command::type::get_accessor 0x7fff56c27290 mode::discard_write target::global_buffer 
command: enqueue_task 
Debug: prepare_kernel _sycl_kernel_0 
command::type::copy_data 0x7fff56c27290 mode::discard_write target::global_buffer mode::read 
Debug: add 0x7fff56c271e0 0x7fff56c27290 
Debug: add 0x7fff56c271e0 0x7fff56c27290 
0 -> expected 0.174901, got 0.768799

./reduction_sum
Queue device information: 
HD Graphics 4000 
OpenCL C 1.2  
FULL_PROFILE 
OpenCL 1.2  
1.2(Jun 30 2016 20:43:33) 


Debug: add 0x7fff5d6d5f60 0x7fff5d6d5ee0 
Debug: add 0x7fff5d6d5f60 0x7fff5d6d5ee0 
Compiled kernel: 
__kernel void _sycl_kernel_0(__global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf1[_sycl_gid] = _sycl_gid;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_3(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_6(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_9(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_12(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_15(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_18(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_21(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_24(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_27(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Compiled kernel: 
__kernel void _sycl_kernel_30(__global int* _sycl_buf2, __global int* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf2[((2 * _sycl_buf1[0]) * _sycl_gid)] += _sycl_buf2[(((2 * _sycl_buf1[0]) * _sycl_gid) + _sycl_buf1[0])];
	_sycl_buf1[0] *= 2;
}
 
Debug: can_flush buffers_in_use 0x7fff5d6d5e60 0x7fff5d6d5ee0 
Debug: can_flush host_accessors 
Debug: can_flush buffers_in_use 0x7fff5d6d5e60 0x7fff5d6d5ee0 
Debug: can_flush host_accessors 
Debug: optimize 
Debug: flush 0x7fd7a2628650 0x7fd7a2711b30 
command: init 
command::type::get_accessor 0x7fff5d6d5e60 mode::read_write target::global_buffer 
command::type::copy_data 0x7fff5d6d5e60 mode::read_write target::global_buffer mode::write 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_0 
command: init 
command::type::get_accessor 0x7fff5d6d5ee0 mode::read_write target::global_buffer 
command::type::copy_data 0x7fff5d6d5ee0 mode::read_write target::global_buffer mode::write 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_3 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_6 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_9 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_12 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_15 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_18 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_21 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_24 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_27 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_30 
command::type::copy_data 0x7fff5d6d5e60 mode::read_write target::global_buffer mode::read 
command::type::copy_data 0x7fff5d6d5ee0 mode::read_write target::global_buffer mode::read 
Debug: add 0x7fff5d6d5f60 0x7fff5d6d5e60 
Debug: add 0x7fff5d6d5f60 0x7fff5d6d5e60 
wrong sum, should be 523776 - is 27296

./reduction_sum_local 
Queue device information: 
HD Graphics 4000 
OpenCL C 1.2  
FULL_PROFILE 
OpenCL 1.2  
1.2(Jun 30 2016 20:43:33) 


Compiled kernel: 
__kernel void _sycl_kernel_0(__global float* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	_sycl_buf1[_sycl_gid] = _sycl_gid;
}
 
Debug: can_flush buffers_in_use 0x7fff58765790 
Debug: can_flush host_accessors 
Debug: can_flush buffers_in_use 0x7fff58765790 
Debug: can_flush host_accessors 
Debug: optimize 
Debug: flush 0x7f89240022a0 0x7f8922433ff0 
command: init 
command::type::get_accessor 0x7fff58765790 mode::write target::global_buffer 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_0 
command::type::copy_data 0x7fff58765790 mode::write target::global_buffer mode::read 
Submitting work 
Debug: operator() 2048 512 
Compiled kernel: 
__kernel void _sycl_kernel_3(__local float* _sycl_buf2, __global const float* _sycl_buf1, __global float* _sycl_buf3) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	const int _sycl_lid0 = get_local_id(0);
	const int _sycl_lid = _sycl_lid0;
	const int _sycl_grange0 = get_global_size(0);
	const int _sycl_grange = _sycl_grange0;
	const int _sycl_lrange0 = get_local_size(0);
	const int _sycl_lrange = _sycl_lrange0;
	uint _uint_0 = _sycl_grange0;
	uint _uint_1 = (_sycl_gid0 + _uint_0);
	if((_uint_1 < (2 * _uint_0))) 
	{ 
		_sycl_buf2[_sycl_lid0] = (_sycl_buf1[_sycl_gid0] + _sycl_buf1[_uint_1]);
	} 
	barrier(CLK_LOCAL_MEM_FENCE);
	uint _uint_2 = _sycl_lrange0;
	_uint_0 = min(_uint_0, _uint_2);
	while( ((_uint_0 / 2) > 0)) 
	{ 
		if((_sycl_lid0 < (_uint_0 / 2))) 
		{ 
			_sycl_buf2[_sycl_lid0] += _sycl_buf2[(_sycl_lid0 + (_uint_0 / 2))];
		} 
		barrier(CLK_LOCAL_MEM_FENCE);
		(_uint_0 / 2) /= 2;
	} 
	if((_sycl_lid0 == 0)) 
	{ 
		_sycl_buf3[(_sycl_gid0 / _uint_0)] = _sycl_buf2[0];
	} 
}
 
SYCL_ERROR::CL_BUILD_PROGRAM_FAILURE 
Error while compiling kernel _sycl_kernel_3 -> 
	While compiling for device HD Graphics 4000 ->
 <program source>:26:17: error: expression is not assignable
                (_uint_0 / 2) /= 2;
  ~~~~~~~~~~~~~ ^
<program source>:21:18: warning: comparison of integers of different signs: 'const int' and 'unsigned int'
                if((_sycl_lid0 < (_uint_0 / 2))) 
      ~~~~~~~~~~ ^  ~~~~~~~~~~~
 
	While compiling for device GeForce GT 650M ->
 <program source>:26:17: error: expression is not assignable
                (_uint_0 / 2) /= 2;
  ~~~~~~~~~~~~~ ^
<program source>:21:18: warning: comparison of integers of different signs: 'const int' and 'unsigned int'
                if((_sycl_lid0 < (_uint_0 / 2))) 
      ~~~~~~~~~~ ^  ~~~~~~~~~~~
 
terminate called after throwing an instance of 'cl::sycl::exception'
Abort trap: 6

./vectors_in_kernel 
Queue device information: 
Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz 
OpenCL C 1.2  
FULL_PROFILE 
OpenCL 1.2  
1.1 


Compiled kernel: 
__kernel void _sycl_kernel_0(__global float3* _sycl_buf1) {
	const int _sycl_gid0 = get_global_id(0);
	const int _sycl_gid = _sycl_gid0;
	float3 _float3_0 = (float3)(1.f, 2.f, 0);
	_sycl_buf1[_sycl_gid] = _float3_0;
	_sycl_buf1[_sycl_gid].s2 = 3.f;
}
 
Debug: can_flush buffers_in_use 
Debug: can_flush host_accessors 
Debug: can_flush buffers_in_use 0x7fff5065d250 
Debug: can_flush host_accessors 
Debug: optimize 
Debug: flush 0x7faa5240c3c0 0x7faa52702cf0 
command: init 
command::type::get_accessor 0x7fff5065d250 mode::discard_write target::global_buffer 
command: enqueue_range 
Debug: prepare_kernel _sycl_kernel_0 
command::type::copy_data 0x7fff5065d250 mode::discard_write target::global_buffer mode::read 
Debug: add 0x7fff5065d1b0 0x7fff5065d250 
Debug: add 0x7fff5065d1b0 0x7fff5065d250

**Comment by ProGTX** [comment]
Thanks for the feedback. Yeah, I know there are regression tests failing. I'm not quite sure what caused that - at some point I was refactoring the project and I guess I must have broken something. I don't have much time to look into it but definitely want to at some point.

As for the Nvidia GPU not being selected, from what I remember it just returns the first GPU device, so that would be Intel in your case. You can reverse the order by reversing the ICD files or writing a custom device selector. I would also like to revise the device selection in order to support cases like yours.

**Pull request merged**
