### PR TITLE
Add hipSYCL

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by ProGTX** [comment]
Hi, I apologize for not approving this earlier. This looks good thank you. I guess we could also add Intel's SYCL compiler.

**Comment by ShalokShalom** [comment]
Yeah, I also thought about this one. In the same style?

**Comment by ProGTX** [comment]
Sure thing. May want to split the implementations into multiple lines, though.

**Comment by ShalokShalom** [comment]
Would you go on?

**Comment by ProGTX** [comment]
Sorry, I'm not sure what you mean.

**Comment by ShalokShalom** [comment]
Would you commit this?

**Pull request merged**
